apiVersion: v1
kind: Secret
metadata:
  name: openfindbearings-api-secrets
  namespace: openfindbearings
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "<db_api 连接串>"
  CacheSettings__RedisConnectionString: "<Redis 连接串>"
